# Generated by Django 5.0.6 on 2024-09-02 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres_name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=150, null=True)),
                ('director', models.CharField(max_length=150, null=True)),
                ('production_company', models.CharField(max_length=150, null=True)),
                ('actors', models.CharField(max_length=150, null=True)),
                ('genre_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_app.genre')),
            ],
        ),
    ]
