# Generated by Django 5.0.6 on 2024-09-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='details',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
