# Generated by Django 5.0.6 on 2024-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0003_movie_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
